######################################################################
# Automatically generated by qmake (3.0) tors jun 26 17:38:42 2014
######################################################################

QT += network
TEMPLATE = app
TARGET = RunClient
INCLUDEPATH += .

# Input
HEADERS += \
    camera.h \
    cube.h \
    window.h \
    client.h

SOURCES += main.cpp \
    cube.cpp
    
unix {
   QMAKE_CXXFLAGS += -std=c++11
}

RESOURCES += \
    shaders.qrc

OTHER_FILES +=
