DEBUG : $(GENERAL_TARGET_DEPENDENCIES) $(MAIN_APPLICATION)

RELEASE : $(GENERAL_TARGET_DEPENDENCIES) $(MAIN_APPLICATION)

UNIT_TEST : $(GENERAL_TARGET_DEPENDENCIES) $(AUTO_SRC_DIR) $(MOCK_DIR) $(UNIT_TEST_BINARIES)
	@$(SHELL) run_all_unit_tests.sh $(BIN_DIR)

HSIT_MASTER : $(GENERAL_TARGET_DEPENDENCIES) $(HSIT_MASTER_BINARIES)

HSIT_SLAVE : $(GENERAL_TARGET_DEPENDENCIES) $(HSIT_SLAVE_BINARIES)
